#!/bin/bash

cd  "$(dirname "$0")"
DIR="$PWD"

[ -d 'dist' ] && rm -rf dist
mkdir dist

cd "$DIR/parser"
[ -d 'node_modules' ] || npm i
[ -d 'dist' ] && rm -rf dist
npx tsc && node dist

cd "$DIR/client"
[ -d 'node_modules' ] || npm i
npx pug -P -o ../dist index.pug
npx sass scss/index.scss ../dist/index.css
npx webpack

cd "$DIR/dist"
HASH="$(md5sum index.css | head -c 10)"
mv index.css "index.${HASH}.css"
mv index.css.map "index.${HASH}.css.map"
perl -p -i -e "s/index\.css/index.${HASH}.css/g" index.html

cd "$DIR"
cp -r assets dist/
