#!/bin/bash

cd  "$(dirname "$0")"
DIR="$PWD"

[ -d 'dist' ] && rm -rf dist
mkdir dist

echo
echo 'CSS'
cd "$DIR/client"
[ -d 'node_modules' ] || npm i
npx sass scss/index.scss ../dist/index.css

echo
echo 'CSS Hash'
cd "$DIR/dist"
HASH="$(md5sum index.css | head -c 10)"
mv index.css "index.${HASH}.css"
mv index.css.map "index.${HASH}.css.map"

echo
echo 'HTML'
cd "$DIR/static-template"
[ -d 'node_modules' ] || npm i
npx tsc -b && npx whits "dist" "$DIR/dist" "{\"hash\": \"$HASH\"}"

echo
echo 'Webpack'
cd "$DIR/client"
npx webpack

echo
echo 'Assets & Books'
cd "$DIR"
cp -r assets dist/
cp books/books.json dist/
